const UI_ROOT = "/assets/ui";

export type UiAssetScale = "original" | "4x";

export function uiAsset(group: string, file: string, _scale: UiAssetScale = "4x") {
  return `${UI_ROOT}/${group}/${file}`;
}

export function cssUrl(url: string) {
  return `url("${url}")`;
}

export const uiAssets = {
  core: {
    buttonPrimaryTeal: uiAsset("01_core-ui", "button_primary_teal__01_core-ui_041.png", "4x"),
    buttonSecondaryParchment: uiAsset("01_core-ui", "button_small_parchment__01_core-ui_038.png", "4x"),
    buttonDangerRed: uiAsset("01_core-ui", "button_danger_red__01_core-ui_042.png", "4x"),
    buttonDisabledDark: uiAsset("01_core-ui", "button_disabled_dark__01_core-ui_044.png", "4x"),
    buttonFilterDark: uiAsset("01_core-ui", "button_filter_dark__01_core-ui_047.png", "4x"),
    iconButtonDarkScales: uiAsset("01_core-ui", "icon_button_dark_scales__01_core-ui_037.png", "4x"),
    iconButtonDangerSwords: uiAsset("01_core-ui", "icon_button_danger_swords__01_core-ui_048.png", "4x"),
    iconButtonMoney: uiAsset("01_core-ui", "icon_button_money__01_core-ui_032.png", "4x"),
    utilityButtonDarkShield: uiAsset("01_core-ui", "utility_button_dark_shield__01_core-ui_033.png", "4x"),
    circularEmblemHolder: uiAsset("01_core-ui", "circular_emblem_holder__01_core-ui_023.png", "4x"),
    cornerOrnamentLeft: uiAsset("01_core-ui", "corner_ornament_left__01_core-ui_016.png", "4x"),
    cornerOrnamentRight: uiAsset("01_core-ui", "corner_ornament_right__01_core-ui_017.png", "4x"),
    pageTitlePlaqueTeal: uiAsset("01_core-ui", "page_title_plaque_teal__01_core-ui_027.png", "4x"),
    sectionHeaderPlaqueWood: uiAsset("01_core-ui", "section_header_plaque_wood__01_core-ui_007.png", "4x"),
    smallTitleRibbonParchment: uiAsset("01_core-ui", "small_title_ribbon_parchment__01_core-ui_028.png", "4x"),
    titleRibbonTealWide: uiAsset("01_core-ui", "title_ribbon_teal_wide__01_core-ui_013.png", "4x"),
    titleRibbonTealSmall: uiAsset("01_core-ui", "title_ribbon_teal_small__01_core-ui_009.png", "4x"),
    panelLargeParchment: uiAsset("01_core-ui", "panel_large_parchment__01_core-ui_004.png", "4x"),
    panelLargeParchmentAlt: uiAsset("01_core-ui", "panel_large_parchment_alt__01_core-ui_006.png", "4x"),
    searchBarParchment: uiAsset("01_core-ui", "search_bar_parchment__01_core-ui_069.png", "4x"),
    dropdownClosed: uiAsset("01_core-ui", "dropdown_closed__01_core-ui_071.png", "4x"),
    checkboxChecked: uiAsset("01_core-ui", "checkbox_checked__01_core-ui_073.png", "4x"),
    checkboxUnchecked: uiAsset("01_core-ui", "checkbox_unchecked__01_core-ui_072.png", "4x"),
    radioChecked: uiAsset("01_core-ui", "radio_checked__01_core-ui_075.png", "4x"),
    radioUnchecked: uiAsset("01_core-ui", "radio_unchecked__01_core-ui_074.png", "4x"),
    statusBarFrameTeal: uiAsset("01_core-ui", "status_bar_frame_teal__01_core-ui_026.png", "4x"),
    ledgerRowStatusStrip: uiAsset("01_core-ui", "ledger_row_status_strip__01_core-ui_078.png", "4x"),
    toastShellPale: uiAsset("01_core-ui", "toast_shell_pale__01_core-ui_084.png", "4x"),
    toastShellTeal: uiAsset("01_core-ui", "toast_shell_teal__01_core-ui_085.png", "4x"),
  },
  inventory: {
    slotEmptyLarge: uiAsset("02_inventory-trade", "inventory_slot_empty_large__02_inventory-trade_013.png", "4x"),
    slotSelectedLarge: uiAsset("02_inventory-trade", "inventory_slot_selected_large__02_inventory-trade_014.png", "4x"),
    slotDisabledLarge: uiAsset("02_inventory-trade", "inventory_slot_disabled_large__02_inventory-trade_015.png", "4x"),
    slotFilledLarge: uiAsset("02_inventory-trade", "inventory_slot_filled_large__02_inventory-trade_016.png", "4x"),
    slotMedium: uiAsset("02_inventory-trade", "inventory_slot_medium__02_inventory-trade_051.png", "4x"),
    slotSmall: uiAsset("02_inventory-trade", "inventory_slot_small__02_inventory-trade_019.png", "4x"),
    slotLockedLarge: uiAsset("02_inventory-trade", "inventory_slot_locked_large__02_inventory-trade_018.png", "4x"),
    slotHighlightGlow: uiAsset("02_inventory-trade", "slot_highlight_glow__02_inventory-trade_012.png", "4x"),
    itemIconFrameLarge: uiAsset("02_inventory-trade", "item_icon_frame_large__02_inventory-trade_043.png", "4x"),
    inventoryToolbarItems: uiAsset("02_inventory-trade", "inventory_toolbar_items__02_inventory-trade_092.png", "4x"),
    searchFilterBar: uiAsset("02_inventory-trade", "search_filter_bar__02_inventory-trade_094.png", "4x"),
    sortDropdown: uiAsset("02_inventory-trade", "sort_dropdown__02_inventory-trade_093.png", "4x"),
    categoryFilterBar: uiAsset("02_inventory-trade", "category_filter_bar__02_inventory-trade_095.png", "4x"),
    bulkActionsDropdown: uiAsset("02_inventory-trade", "bulk_actions_dropdown__02_inventory-trade_096.png", "4x"),
    valueBalancePanel: uiAsset("02_inventory-trade", "value_balance_panel__02_inventory-trade_067.png", "4x"),
    valueComparisonPlaque: uiAsset("02_inventory-trade", "value_comparison_plaque__02_inventory-trade_053.png", "4x"),
    fairnessMeterEmpty: uiAsset("02_inventory-trade", "fairness_meter_empty__02_inventory-trade_065.png", "4x"),
    offerSlotsPlayerStrip: uiAsset("02_inventory-trade", "offer_slots_player_strip__02_inventory-trade_066.png", "4x"),
    selectedItemInspectorPanel: uiAsset("02_inventory-trade", "selected_item_inspector_panel__02_inventory-trade_044.png", "4x"),
    itemDetailChecklistPanel: uiAsset("02_inventory-trade", "item_detail_checklist_panel__02_inventory-trade_110.png", "4x"),
    detailPortraitVase: uiAsset("02_inventory-trade", "detail_portrait_vase__02_inventory-trade_138.png", "4x"),
    badgeRarityStar: uiAsset("02_inventory-trade", "badge_rarity_star__02_inventory-trade_034.png", "4x"),
    badgeStackQuantity: uiAsset("02_inventory-trade", "badge_stack_quantity_99__02_inventory-trade_031.png", "4x"),
    badgeValueCoin: uiAsset("02_inventory-trade", "badge_value_coin__02_inventory-trade_046.png", "4x"),
    badgeSizeCrate: uiAsset("02_inventory-trade", "badge_size_crate__02_inventory-trade_045.png", "4x"),
    rarityLabelPlaque: uiAsset("02_inventory-trade", "rarity_label_plaque__02_inventory-trade_052.png", "4x"),
    capacityPlaque: uiAsset("02_inventory-trade", "inventory_capacity_plaque__02_inventory-trade_097.png", "4x"),
    markerProtected: uiAsset("02_inventory-trade", "marker_protected_star__02_inventory-trade_020.png", "4x"),
    markerQuest: uiAsset("02_inventory-trade", "marker_quest_item__02_inventory-trade_021.png", "4x"),
    markerIllegal: uiAsset("02_inventory-trade", "marker_illegal_item__02_inventory-trade_023.png", "4x"),
    markerRare: uiAsset("02_inventory-trade", "marker_rare_gold_diamond__02_inventory-trade_027.png", "4x"),
  },
  town: {
    rosterRowDefault: uiAsset("03_npc-town", "roster_row_hover_parchment__03_npc-town_017.png", "4x"),
    rosterRowSelected: uiAsset("03_npc-town", "roster_row_with_like_dislike_actions__03_npc-town_027.png", "4x"),
    rosterRowQuest: uiAsset("03_npc-town", "roster_row_with_quest_marker__03_npc-town_040.png", "4x"),
    rosterRowStock: uiAsset("03_npc-town", "roster_row_with_stock_preview__03_npc-town_042.png", "4x"),
    circularPortraitFrame: uiAsset("03_npc-town", "circular_portrait_frame__03_npc-town_011.png", "4x"),
    portraitFrameLarge: uiAsset("03_npc-town", "portrait_frame_large_plain__03_npc-town_004.png", "4x"),
    portraitFrameSelected: uiAsset("03_npc-town", "portrait_frame_large_selected_teal__03_npc-town_006.png", "4x"),
    moodPositive: uiAsset("03_npc-town", "preferred_by_badge_round__03_npc-town_033.png", "4x"),
    moodNegative: uiAsset("03_npc-town", "disliked_by_badge_round__03_npc-town_034.png", "4x"),
    tradeStyleBadge: uiAsset("03_npc-town", "trade_style_badge_hourglass__03_npc-town_023.png", "4x"),
    relationshipBadge: uiAsset("03_npc-town", "relationship_badge_scales__03_npc-town_025.png", "4x"),
    trustMeterPanel: uiAsset("03_npc-town", "trust_meter_panel__03_npc-town_060.png", "4x"),
    cityBannerPlaque: uiAsset("03_npc-town", "city_banner_plaque__03_npc-town_055.png", "4x"),
    localServicesGrid: uiAsset("03_npc-town", "local_services_grid__03_npc-town_072.png", "4x"),
    serviceTrade: uiAsset("03_npc-town", "service_icon_trade_anchor__03_npc-town_045.png", "4x"),
    serviceMap: uiAsset("03_npc-town", "service_icon_map_stag__03_npc-town_046.png", "4x"),
    serviceCompany: uiAsset("03_npc-town", "service_icon_company_crown__03_npc-town_047.png", "4x"),
    serviceJournal: uiAsset("03_npc-town", "service_icon_journal_book__03_npc-town_065.png", "4x"),
    serviceNotice: uiAsset("03_npc-town", "service_icon_notice_board__03_npc-town_066.png", "4x"),
  },
  map: {
    mapSidePanel: uiAsset("04_map-modal", "map_side_panel__04_map-modal_002.png", "4x"),
    routeDetailsPanel: uiAsset("04_map-modal", "route_details_panel__04_map-modal_003.png", "4x"),
    marketInfoSidePanel: uiAsset("04_map-modal", "market_info_side_panel__04_map-modal_004.png", "4x"),
    routeListLedgerStrip: uiAsset("04_map-modal", "route_list_ledger_strip__04_map-modal_005.png", "4x"),
    worldMapBackgroundTile: uiAsset("04_map-modal", "world_map_background_tile__04_map-modal_006.png", "4x"),
    compassOrnament: uiAsset("04_map-modal", "compass_ornament__04_map-modal_007.png", "4x"),
    legendBox: uiAsset("04_map-modal", "legend_box__04_map-modal_008.png", "4x"),
    closeButtonOrnate: uiAsset("04_map-modal", "close_button_ornate__04_map-modal_055.png", "4x"),
    currentLocationMarker: uiAsset("04_map-modal", "current_location_marker__04_map-modal_015.png", "4x"),
    capitalCityMarker: uiAsset("04_map-modal", "capital_city_marker__04_map-modal_009.png", "4x"),
    portCityMarker: uiAsset("04_map-modal", "port_city_marker__04_map-modal_011.png", "4x"),
    villageMarker: uiAsset("04_map-modal", "village_marker__04_map-modal_012.png", "4x"),
    friendlyCityMarker: uiAsset("04_map-modal", "friendly_city_marker__04_map-modal_016.png", "4x"),
    hostileCityMarker: uiAsset("04_map-modal", "hostile_city_marker__04_map-modal_013.png", "4x"),
    curvedRouteLine: uiAsset("04_map-modal", "curved_route_line__04_map-modal_026.png", "4x"),
    dangerousRouteLine: uiAsset("04_map-modal", "dangerous_route_line__04_map-modal_027.png", "4x"),
    dottedRouteLine: uiAsset("04_map-modal", "dotted_route_line__04_map-modal_030.png", "4x"),
    straightRouteLine: uiAsset("04_map-modal", "straight_route_line__04_map-modal_028.png", "4x"),
    warningToast: uiAsset("04_map-modal", "warning_toast__04_map-modal_043.png", "4x"),
    travelDaysIcon: uiAsset("04_map-modal", "travel_days_icon__04_map-modal_021.png", "4x"),
    tollIcon: uiAsset("04_map-modal", "toll_icon__04_map-modal_020.png", "4x"),
    riskIcon: uiAsset("04_map-modal", "risk_icon__04_map-modal_022.png", "4x"),
  },
  backplates: {
    mainMenuHarbor: uiAsset("05_backplates", "main_menu_harbor_backdrop__05_backplates_001.png", "4x"),
    marketTown: uiAsset("05_backplates", "bright_coastal_market_town_backdrop__05_backplates_003.png", "4x"),
    travelMap: uiAsset("05_backplates", "travel_map_parchment_backdrop__05_backplates_006.png", "4x"),
    warehouseInventory: uiAsset("05_backplates", "warehouse_inventory_room_backdrop__05_backplates_007.png", "4x"),
    saveLoadArchiveRoom: uiAsset("05_backplates", "save_load_archive_room_backdrop__05_backplates_011.png", "4x"),
    tradeConversation: uiAsset("05_backplates", "trade_conversation_backdrop__05_backplates_010.png", "4x"),
    settingsRoom: uiAsset("05_backplates", "settings_room_study_backdrop__05_backplates_012.png", "4x"),
  },
  nineSlice: {
    textureParchmentClean: uiAsset("06_nine-slice", "texture_parchment_clean__06_nine-slice_138.png", "4x"),
    textureParchmentSplattered: uiAsset("06_nine-slice", "texture_parchment_splattered__06_nine-slice_136.png", "4x"),
    textureWoodDark: uiAsset("06_nine-slice", "texture_wood_dark__06_nine-slice_139.png", "4x"),
    textureLeatherBrown: uiAsset("06_nine-slice", "texture_leather_brown__06_nine-slice_140.png", "4x"),
    textureEnamelBlue: uiAsset("06_nine-slice", "texture_enamel_blue__06_nine-slice_142.png", "4x"),
    headerStripTealOrnate: uiAsset("06_nine-slice", "header_strip_teal_ornate__06_nine-slice_077.png", "4x"),
    headerStripRedOrnate: uiAsset("06_nine-slice", "header_strip_red_ornate__06_nine-slice_085.png", "4x"),
    dividerBrass: uiAsset("06_nine-slice", "ornamental_separator_brass_center__06_nine-slice_088.png", "4x"),
    woodFrameFill: uiAsset("06_nine-slice", "wood_frame_fill_b__06_nine-slice_012.png", "4x"),
    modalWoodFill: uiAsset("06_nine-slice", "frame_wood_modal_fill_a__06_nine-slice_057.png", "4x"),
  },
  hud: {
    day: uiAsset("07_hud-icons", "day_sun_icon__07_hud-icons_003.png", "4x"),
    purse: uiAsset("07_hud-icons", "purse_icon__07_hud-icons_004.png", "4x"),
    wealth: uiAsset("07_hud-icons", "wealth_bag_coin_icon__07_hud-icons_009.png", "4x"),
    weight: uiAsset("07_hud-icons", "weight_scale_icon__07_hud-icons_010.png", "4x"),
    goldCoin: uiAsset("07_hud-icons", "gold_coin_icon__07_hud-icons_013.png", "4x"),
    inventory: uiAsset("07_hud-icons", "inventory_icon__07_hud-icons_054.png", "4x"),
    market: uiAsset("07_hud-icons", "market_hub_icon__07_hud-icons_053.png", "4x"),
    search: uiAsset("07_hud-icons", "search_icon__07_hud-icons_055.png", "4x"),
    soundOn: uiAsset("07_hud-icons", "sound_on_icon__07_hud-icons_048.png", "4x"),
    soundOff: uiAsset("07_hud-icons", "sound_off_icon__07_hud-icons_049.png", "4x"),
    warning: uiAsset("07_hud-icons", "warning_icon__07_hud-icons_044.png", "4x"),
  },
  micro: {
    overlayModalDim: uiAsset("08_micro", "overlay_modal_dim__08_micro_082.png", "4x"),
    tabActive: uiAsset("08_micro", "tab_active_leather__08_micro_016.png", "4x"),
    tabInactive: uiAsset("08_micro", "tab_inactive_leather__08_micro_017.png", "4x"),
    tabWarning: uiAsset("08_micro", "tab_warning_leather__08_micro_019.png", "4x"),
    tabDisabled: uiAsset("08_micro", "tab_disabled_leather__08_micro_020.png", "4x"),
    loadingHourglass: uiAsset("08_micro", "loading_hourglass__08_micro_047.png", "4x"),
    scrollbarThumbVerticalTeal: uiAsset("08_micro", "scrollbar_thumb_vertical_teal__08_micro_005.png", "4x"),
  },
} as const;
