import type { CharacterExpressionProfile, CharacterIdentityCatalogBatch, FinalCharacterIdentityProfile } from "../types";
import { getIdentityBatchPortraitImageCount } from "../types";

const majorExpressions = [
  {
    expression: "neutral",
    actingDirection: "calm readable neutral expression, relaxed mouth, direct eye contact, identity anchors unchanged",
    promptDelta: "calm readable neutral expression, relaxed mouth, direct eye contact, identity anchors unchanged",
  },
  {
    expression: "happy",
    actingDirection: "happy expression, genuine profession-appropriate smile, brighter eyes, identity anchors unchanged",
    promptDelta: "happy expression, genuine profession-appropriate smile, brighter eyes, identity anchors unchanged",
  },
  {
    expression: "suspicious",
    actingDirection: "suspicious expression, narrowed eyes, guarded mouth, slight backward lean, identity anchors unchanged",
    promptDelta: "suspicious expression, narrowed eyes, guarded mouth, slight backward lean, identity anchors unchanged",
  },
  {
    expression: "worried",
    actingDirection: "worried expression, tense brow, compressed mouth, shoulders slightly raised, identity anchors unchanged",
    promptDelta: "worried expression, tense brow, compressed mouth, shoulders slightly raised, identity anchors unchanged",
  },
  {
    expression: "angry",
    actingDirection: "angry expression, hard stare, tightened jaw, controlled anger, identity anchors unchanged",
    promptDelta: "angry expression, hard stare, tightened jaw, controlled anger, identity anchors unchanged",
  },
] as const satisfies readonly CharacterExpressionProfile[];

const merchantExpressions = [
  {
    expression: "neutral",
    actingDirection: "calm readable neutral expression, relaxed mouth, direct eye contact, identity anchors unchanged",
    promptDelta: "calm readable neutral expression, relaxed mouth, direct eye contact, identity anchors unchanged",
  },
  {
    expression: "happy",
    actingDirection: "happy expression, genuine profession-appropriate smile, brighter eyes, identity anchors unchanged",
    promptDelta: "happy expression, genuine profession-appropriate smile, brighter eyes, identity anchors unchanged",
  },
  {
    expression: "suspicious",
    actingDirection: "suspicious expression, narrowed eyes, guarded mouth, slight backward lean, identity anchors unchanged",
    promptDelta: "suspicious expression, narrowed eyes, guarded mouth, slight backward lean, identity anchors unchanged",
  },
] as const satisfies readonly CharacterExpressionProfile[];

const minorExpressions = [
  {
    expression: "neutral",
    actingDirection: "calm readable neutral expression, relaxed mouth, direct eye contact, identity anchors unchanged",
    promptDelta: "calm readable neutral expression, relaxed mouth, direct eye contact, identity anchors unchanged",
  },
] as const satisfies readonly CharacterExpressionProfile[];

const sharedNegativePrompt = "no text, no labels, no letters, no numbers, no watermark, no UI frame, no visible border, no visible grid lines, no colored cell panels, no cropped head, no cropped shoulders, no cropped hands, no cropped props, no prop touching edge, no extra limbs, no full-body scene, no photorealism, no anime, no modern clothes, no sci-fi, no gritty realism, no boring plain medieval worker, no generic identical NPC face, no duplicate faces across different characters, no busy background, no gradient background";

const finalSupportingCastIdentities = [
  {
    characterId: "character-211",
    rosterGroup: "supporting_cast",
    runtimeIndex: 162,
    catalogKey: null,
    finalDisplayName: "Duchess Nima Glassvale",
    profession: "Noble Investor",
    gameplayGroups: ["company", "guild_noble", "quest"],
    roleTags: ["investor", "noble", "ledger", "patron", "shareholder"],
    marketFlavor: "sunlit counting salon",
    voiceDirection: "silken, amused, and dangerous when numbers disappoint her",
    tradePersonality: "wealthy patron who rewards reliability and punishes vague promises",
    shortStory: "Nima inherited three warehouses and doubled them by lending only to merchants who could explain a crate's journey from nail to sale. She enjoys funding risky ventures, but every smile hides a ledger column.",
    visualIdentity: "A graceful moon-touched half-elf duchess with warm brown skin, silver-lavender eyes, a waterfall of dark curls pinned by glass beads, emerald velvet sleeves, and a crystal abacus draped over one wrist.",
    uniquenessTraits: ["moon-touched half-elf elegance", "silver-lavender eyes", "glass bead hair pins", "emerald velvet sleeves", "crystal abacus", "long poised fingers"],
    professionProps: ["crystal abacus", "sealed investment letters", "tiny share ledger"],
    dominantColors: ["emerald", "glass blue", "warm gold"],
    expressionTier: "major",
    plannedExpressions: majorExpressions,
    portraitFilePrefix: "character-211",
    identityAnchor: "same person as character-211: moon-touched half-elf elegance, silver-lavender eyes, glass bead hair pins, emerald velvet sleeves, crystal abacus, noble investor, moon-touched half-elf, crystal abacus",
    portraitBasePrompt: "A graceful moon-touched half-elf duchess with warm brown skin, silver-lavender eyes, a waterfall of dark curls pinned by glass beads, emerald velvet sleeves, and a crystal abacus draped over one wrist. stylized medieval fantasy merchant RPG portrait art, polished painterly-cartoon PC game UI look, slightly cartoony, beautiful, charming, expressive, entertaining, natural facial acting, clear profession silhouette, varied body shapes, rich costume accents, crop-safe bust portrait, one flat solid pure green #00FF00 background",
    negativePrompt: sharedNegativePrompt,
    questHooks: ["risky investment", "warehouse expansion", "silent shareholder demand"],
    integrationNotes: "Major investor/patron for company and warehouse progression.",
    ancestryOrSpecies: "moon-touched half-elf",
    magicalTraits: ["faint moonlit glints in the glass beads"],
  },
  {
    characterId: "character-212",
    rosterGroup: "supporting_cast",
    runtimeIndex: 163,
    catalogKey: null,
    finalDisplayName: "Master Threlk Mudhorn",
    profession: "Quarry Factor",
    gameplayGroups: ["trade", "company", "travel"],
    roleTags: ["stone", "quarry", "bulk", "construction", "supplier"],
    marketFlavor: "stone yard below the western gate",
    voiceDirection: "deep, slow, and practical, like a cart grinding uphill",
    tradePersonality: "bulk supplier who favors honest weights and sturdy carts",
    shortStory: "Threlk can judge a block of marble by tapping it with one knuckle. He sells stone, lime, and labor contracts, but quietly sponsors road repairs for villages that cannot pay.",
    visualIdentity: "A massive ogre-kin quarry factor with mossy grey skin, small amber eyes, blunt tusks, a cracked leather apron, chalk marks on his forearms, and a miniature stone sample hanging from a chain.",
    uniquenessTraits: ["massive ogre-kin build", "mossy grey skin", "blunt tusks", "chalk-marked forearms", "cracked leather apron", "stone-sample necklace"],
    professionProps: ["stone sample", "chalk stick", "quarry tally board"],
    dominantColors: ["slate grey", "chalk white", "leather brown"],
    expressionTier: "major",
    plannedExpressions: majorExpressions,
    portraitFilePrefix: "character-212",
    identityAnchor: "same person as character-212: massive ogre-kin build, mossy grey skin, blunt tusks, chalk-marked forearms, cracked leather apron, quarry factor, ogre-kin, stone sample",
    portraitBasePrompt: "A massive ogre-kin quarry factor with mossy grey skin, small amber eyes, blunt tusks, a cracked leather apron, chalk marks on his forearms, and a miniature stone sample hanging from a chain. stylized medieval fantasy merchant RPG portrait art, polished painterly-cartoon PC game UI look, slightly cartoony, beautiful, charming, expressive, entertaining, natural facial acting, clear profession silhouette, varied body shapes, rich costume accents, crop-safe bust portrait, one flat solid pure green #00FF00 background",
    negativePrompt: sharedNegativePrompt,
    questHooks: ["road repair order", "missing stone shipment", "quarry labor dispute"],
    integrationNotes: "Major bulk material contact for construction, travel routes, and warehouse expansion.",
    ancestryOrSpecies: "ogre-kin",
    magicalTraits: [],
  },
  {
    characterId: "character-213",
    rosterGroup: "supporting_cast",
    runtimeIndex: 164,
    catalogKey: null,
    finalDisplayName: "Sister Pavi Embermoth",
    profession: "Relic Hospice Keeper",
    gameplayGroups: ["quest", "trade", "market_service"],
    roleTags: ["religious", "medicine", "relic", "charity", "rumor"],
    marketFlavor: "quiet hospice by the candle stairs",
    voiceDirection: "gentle, patient, but capable of making a thief feel ashamed",
    tradePersonality: "charitable healer who pays fairly for clean linen, candles, herbs, and relic containers",
    shortStory: "Pavi tends sick pilgrims beside a wall of tiny flame-moth lamps. She knows which relics are fake, which saints were frauds, and which merchants still deserve mercy.",
    visualIdentity: "A soft round halfling nun with cinnamon skin, kind tired eyes, a cream hood dotted with ember-moth embroidery, soot-smudged fingertips, and a little lantern full of orange moth-light.",
    uniquenessTraits: ["short round halfling silhouette", "kind tired eyes", "ember-moth hood embroidery", "soot-smudged fingertips", "little moth lantern", "soft cream robes"],
    professionProps: ["moth lantern", "healing linen", "wax prayer seals"],
    dominantColors: ["cream", "ember orange", "soft brown"],
    expressionTier: "major",
    plannedExpressions: majorExpressions,
    portraitFilePrefix: "character-213",
    identityAnchor: "same person as character-213: short round halfling silhouette, kind tired eyes, ember-moth hood embroidery, soot-smudged fingertips, little moth lantern, relic hospice keeper, halfling, moth lantern",
    portraitBasePrompt: "A soft round halfling nun with cinnamon skin, kind tired eyes, a cream hood dotted with ember-moth embroidery, soot-smudged fingertips, and a little lantern full of orange moth-light. stylized medieval fantasy merchant RPG portrait art, polished painterly-cartoon PC game UI look, slightly cartoony, beautiful, charming, expressive, entertaining, natural facial acting, clear profession silhouette, varied body shapes, rich costume accents, crop-safe bust portrait, one flat solid pure green #00FF00 background",
    negativePrompt: sharedNegativePrompt,
    questHooks: ["sick pilgrim cure", "true relic test", "missing hospice candles"],
    integrationNotes: "Religious/healing quest NPC with strong market-service value.",
    ancestryOrSpecies: "halfling",
    magicalTraits: ["tiny harmless ember moths glowing inside her lantern"],
  },
  {
    characterId: "character-214",
    rosterGroup: "supporting_cast",
    runtimeIndex: 165,
    catalogKey: null,
    finalDisplayName: "Veyra Knotsong",
    profession: "Witch Cartographer",
    gameplayGroups: ["travel", "quest", "collector_specialist"],
    roleTags: ["map", "route", "magic", "rumor", "danger"],
    marketFlavor: "windy map stall tied with red thread",
    voiceDirection: "playful, sings bad news before saying it plainly",
    tradePersonality: "route specialist who values odd inks, feathers, compasses, and stories from dangerous roads",
    shortStory: "Veyra draws maps that hum when a route turns unlucky. Caravan masters pretend not to believe in her thread-charms, then buy three before leaving town.",
    visualIdentity: "A wiry dark-skinned human witch-cartographer with asymmetrical white braids, bright teal eye paint, a crooked grin, patched red shawl, and a map covered in singing thread knots.",
    uniquenessTraits: ["wiry dancing posture", "asymmetrical white braids", "teal eye paint", "crooked grin", "patched red shawl", "singing thread map"],
    professionProps: ["thread-covered map", "bone compass", "red route knots"],
    dominantColors: ["red thread", "teal", "aged parchment"],
    expressionTier: "major",
    plannedExpressions: majorExpressions,
    portraitFilePrefix: "character-214",
    identityAnchor: "same person as character-214: wiry dancing posture, asymmetrical white braids, teal eye paint, crooked grin, patched red shawl, witch cartographer, human, thread-covered map",
    portraitBasePrompt: "A wiry dark-skinned human witch-cartographer with asymmetrical white braids, bright teal eye paint, a crooked grin, patched red shawl, and a map covered in singing thread knots. stylized medieval fantasy merchant RPG portrait art, polished painterly-cartoon PC game UI look, slightly cartoony, beautiful, charming, expressive, entertaining, natural facial acting, clear profession silhouette, varied body shapes, rich costume accents, crop-safe bust portrait, one flat solid pure green #00FF00 background",
    negativePrompt: sharedNegativePrompt,
    questHooks: ["cursed shortcut", "lost route song", "map ink ingredient"],
    integrationNotes: "Major magical route and risk preview contact.",
    ancestryOrSpecies: "human",
    magicalTraits: ["floating red thread knots that hum around the map"],
  },
  {
    characterId: "character-215",
    rosterGroup: "supporting_cast",
    runtimeIndex: 166,
    catalogKey: null,
    finalDisplayName: "Captain Salo Redwake",
    profession: "Retired Privateer Fence",
    gameplayGroups: ["risk_crime", "trade", "quest"],
    roleTags: ["fence", "dock", "contraband", "pirate", "rare_goods"],
    marketFlavor: "back room behind a sailmaker",
    voiceDirection: "charming, wickedly amused, always one joke away from a threat",
    tradePersonality: "contraband-friendly buyer who pays for risk but remembers betrayal",
    shortStory: "Salo insists he retired from piracy because ships became boring, not because of the royal pardon nailed to his wall. He moves rare goods through dock whispers and never asks where jewels learned to smell like seawater.",
    visualIdentity: "A handsome one-eyed river-touched man with sea-green skin undertones, a red silk sash, curled black moustache, pearl earring, half-smile, and a small hook-shaped pipe kept safely inside the portrait.",
    uniquenessTraits: ["one-eyed privateer charm", "sea-green undertones", "red silk sash", "curled black moustache", "pearl earring", "hook-shaped pipe"],
    professionProps: ["hook-shaped pipe", "black-market ledger", "pearl earring"],
    dominantColors: ["red silk", "sea green", "pearl white"],
    expressionTier: "major",
    plannedExpressions: majorExpressions,
    portraitFilePrefix: "character-215",
    identityAnchor: "same person as character-215: one-eyed privateer charm, sea-green undertones, red silk sash, curled black moustache, pearl earring, retired privateer fence, river-touched human, hook-shaped pipe",
    portraitBasePrompt: "A handsome one-eyed river-touched man with sea-green skin undertones, a red silk sash, curled black moustache, pearl earring, half-smile, and a small hook-shaped pipe kept safely inside the portrait. stylized medieval fantasy merchant RPG portrait art, polished painterly-cartoon PC game UI look, slightly cartoony, beautiful, charming, expressive, entertaining, natural facial acting, clear profession silhouette, varied body shapes, rich costume accents, crop-safe bust portrait, one flat solid pure green #00FF00 background",
    negativePrompt: sharedNegativePrompt,
    questHooks: ["forgiven pirate debt", "illegal pearl buyer", "dock ambush warning"],
    integrationNotes: "Major risk/crime and black-market trade contact.",
    ancestryOrSpecies: "river-touched human",
    magicalTraits: ["subtle watery shine in his remaining eye"],
  },
  {
    characterId: "character-216",
    rosterGroup: "supporting_cast",
    runtimeIndex: 167,
    catalogKey: null,
    finalDisplayName: "Miri Ninekeys",
    profession: "Vault Banker",
    gameplayGroups: ["company", "market_service", "guild_noble"],
    roleTags: ["bank", "vault", "loan", "shares", "security"],
    marketFlavor: "brass vault office",
    voiceDirection: "quick, exact, friendly only after collateral is named",
    tradePersonality: "banker who trades in credit, security, and careful introductions",
    shortStory: "Miri wears nine keys but claims only seven open anything real. She arranges loans, stores sealed deeds, and can smell a forged signature before the ink dries.",
    visualIdentity: "A tiny elderly gnome banker with warm mahogany skin, enormous round spectacles, a tower of braided silver hair, navy waistcoat, nine brass keys across her chest, and a ledger almost bigger than she is.",
    uniquenessTraits: ["tiny elderly gnome", "tower of braided silver hair", "huge round spectacles", "navy waistcoat", "nine brass keys", "oversized ledger"],
    professionProps: ["nine brass keys", "vault ledger", "loan seal"],
    dominantColors: ["navy", "brass", "mahogany"],
    expressionTier: "major",
    plannedExpressions: majorExpressions,
    portraitFilePrefix: "character-216",
    identityAnchor: "same person as character-216: tiny elderly gnome, tower of braided silver hair, huge round spectacles, navy waistcoat, nine brass keys, vault banker, gnome, nine brass keys",
    portraitBasePrompt: "A tiny elderly gnome banker with warm mahogany skin, enormous round spectacles, a tower of braided silver hair, navy waistcoat, nine brass keys across her chest, and a ledger almost bigger than she is. stylized medieval fantasy merchant RPG portrait art, polished painterly-cartoon PC game UI look, slightly cartoony, beautiful, charming, expressive, entertaining, natural facial acting, clear profession silhouette, varied body shapes, rich costume accents, crop-safe bust portrait, one flat solid pure green #00FF00 background",
    negativePrompt: sharedNegativePrompt,
    questHooks: ["collateral dispute", "missing vault key", "shareholder records"],
    integrationNotes: "Major company/banking contact for loans, shares, and warehouse documents.",
    ancestryOrSpecies: "gnome",
    magicalTraits: [],
  },
  {
    characterId: "character-217",
    rosterGroup: "supporting_cast",
    runtimeIndex: 168,
    catalogKey: null,
    finalDisplayName: "Jorun Sweetbarrel",
    profession: "Preserve Maker",
    gameplayGroups: ["trade", "quest"],
    roleTags: ["food", "preserves", "fruit", "barrel", "supplier"],
    marketFlavor: "sticky jam stall",
    voiceDirection: "warm, loud, and slightly scandalized by bad fruit",
    tradePersonality: "bulk food seller who overbuys seasonal fruit and clean jars",
    shortStory: "Jorun turns bruised fruit into jams that make caravan guards homesick. His secret is singing to the barrels, though he insists the barrels sing first.",
    visualIdentity: "A broad cheerful human man with rosy cheeks, curly auburn beard, honey-yellow apron, sleeves rolled up, and little jam jars tied with blue ribbons.",
    uniquenessTraits: ["broad cheerful build", "rosy cheeks", "curly auburn beard", "honey apron", "blue jar ribbons", "sticky smile"],
    professionProps: ["jam jars", "small barrel", "wooden spoon"],
    dominantColors: ["honey yellow", "berry red", "ribbon blue"],
    expressionTier: "merchant",
    plannedExpressions: merchantExpressions,
    portraitFilePrefix: "character-217",
    identityAnchor: "same person as character-217: broad cheerful build, rosy cheeks, curly auburn beard, honey apron, blue jar ribbons, preserve maker, human, jam jars",
    portraitBasePrompt: "A broad cheerful human man with rosy cheeks, curly auburn beard, honey-yellow apron, sleeves rolled up, and little jam jars tied with blue ribbons. stylized medieval fantasy merchant RPG portrait art, polished painterly-cartoon PC game UI look, slightly cartoony, beautiful, charming, expressive, entertaining, natural facial acting, clear profession silhouette, varied body shapes, rich costume accents, crop-safe bust portrait, one flat solid pure green #00FF00 background",
    negativePrompt: sharedNegativePrompt,
    questHooks: ["spoiled fruit rescue", "festival jam order", "singing barrel rumor"],
    integrationNotes: "Food/preserve merchant with bulk supply hooks.",
    ancestryOrSpecies: "human",
    magicalTraits: [],
  },
  {
    characterId: "character-218",
    rosterGroup: "supporting_cast",
    runtimeIndex: 169,
    catalogKey: null,
    finalDisplayName: "Laleh Copperkettle",
    profession: "Coffee And Tea Brewer",
    gameplayGroups: ["trade", "market_service"],
    roleTags: ["drink", "tea", "coffee", "spice", "rumor"],
    marketFlavor: "steaming kettle corner",
    voiceDirection: "fast, witty, and impossible to leave without hearing gossip",
    tradePersonality: "buys spices, herbs, clean cups, and foreign beans",
    shortStory: "Laleh can tell a traveler's route by the dust in their throat. Her copper kettles never stop singing, and neither do her customers.",
    visualIdentity: "A slim djinn-blooded woman with bronze skin, bright turquoise scarf, copper curls, hennaed hands, and three tiny steaming kettles floating near her shoulder.",
    uniquenessTraits: ["slim bronze silhouette", "copper curls", "turquoise scarf", "hennaed hands", "floating kettles", "sharp smile"],
    professionProps: ["copper kettles", "tea cups", "spice tin"],
    dominantColors: ["turquoise", "copper", "steam white"],
    expressionTier: "merchant",
    plannedExpressions: merchantExpressions,
    portraitFilePrefix: "character-218",
    identityAnchor: "same person as character-218: slim bronze silhouette, copper curls, turquoise scarf, hennaed hands, floating kettles, coffee and tea brewer, djinn-blooded human, copper kettles",
    portraitBasePrompt: "A slim djinn-blooded woman with bronze skin, bright turquoise scarf, copper curls, hennaed hands, and three tiny steaming kettles floating near her shoulder. stylized medieval fantasy merchant RPG portrait art, polished painterly-cartoon PC game UI look, slightly cartoony, beautiful, charming, expressive, entertaining, natural facial acting, clear profession silhouette, varied body shapes, rich costume accents, crop-safe bust portrait, one flat solid pure green #00FF00 background",
    negativePrompt: sharedNegativePrompt,
    questHooks: ["rare bean shipment", "spiced rumor", "sleeping caravan cure"],
    integrationNotes: "Drink merchant and rumor source.",
    ancestryOrSpecies: "djinn-blooded human",
    magicalTraits: ["three tiny steaming kettles floating safely near her shoulder"],
  },
  {
    characterId: "character-219",
    rosterGroup: "supporting_cast",
    runtimeIndex: 170,
    catalogKey: null,
    finalDisplayName: "Fen Bristlecap",
    profession: "Mushroom Forager",
    gameplayGroups: ["trade", "travel"],
    roleTags: ["mushroom", "forager", "food", "forest", "medicine"],
    marketFlavor: "damp mushroom awning",
    voiceDirection: "soft, earthy, and suspicious of sunshine",
    tradePersonality: "forest supplier who buys baskets, salt, and clean knives",
    shortStory: "Fen knows which mushrooms dream and which ones bite. He sells safe caps to cooks and strange caps to apothecaries, and keeps the dangerous ones under his hat.",
    visualIdentity: "A squat halfling forager with olive-brown skin, mossy green cloak, mushroom-shaped red cap, wide nose, muddy boots, and a basket of colorful fungi.",
    uniquenessTraits: ["squat halfling shape", "mushroom-shaped red cap", "wide nose", "moss cloak", "muddy boots", "fungi basket"],
    professionProps: ["fungi basket", "small knife", "moss cloak"],
    dominantColors: ["moss green", "red cap", "mud brown"],
    expressionTier: "merchant",
    plannedExpressions: merchantExpressions,
    portraitFilePrefix: "character-219",
    identityAnchor: "same person as character-219: squat halfling shape, mushroom-shaped red cap, wide nose, moss cloak, muddy boots, mushroom forager, halfling, fungi basket",
    portraitBasePrompt: "A squat halfling forager with olive-brown skin, mossy green cloak, mushroom-shaped red cap, wide nose, muddy boots, and a basket of colorful fungi. stylized medieval fantasy merchant RPG portrait art, polished painterly-cartoon PC game UI look, slightly cartoony, beautiful, charming, expressive, entertaining, natural facial acting, clear profession silhouette, varied body shapes, rich costume accents, crop-safe bust portrait, one flat solid pure green #00FF00 background",
    negativePrompt: sharedNegativePrompt,
    questHooks: ["poison cap confusion", "forest shortcut", "chef's rare mushroom"],
    integrationNotes: "Forest food/medicine supplier.",
    ancestryOrSpecies: "halfling",
    magicalTraits: [],
  },
  {
    characterId: "character-220",
    rosterGroup: "supporting_cast",
    runtimeIndex: 171,
    catalogKey: null,
    finalDisplayName: "Osha Moonneedle",
    profession: "Moonlit Tailor",
    gameplayGroups: ["trade", "guild_noble"],
    roleTags: ["cloth", "tailor", "fashion", "noble", "repair"],
    marketFlavor: "silver-thread sewing booth",
    voiceDirection: "smooth, precise, and a little vain about hems",
    tradePersonality: "tailor who values silk, dyes, thread, and rare buttons",
    shortStory: "Osha stitches formal sleeves for nobles and hidden pockets for smugglers, pretending both are the same craft. Her moon-thread glimmers only when a customer lies about their measurements.",
    visualIdentity: "A tall moon-touched half-elf tailor with pale golden skin, short silver bob, crescent earrings, violet measuring sash, and a needle that glows faintly blue.",
    uniquenessTraits: ["tall elegant half-elf", "short silver bob", "crescent earrings", "violet measuring sash", "glowing needle", "long graceful neck"],
    professionProps: ["glowing needle", "measuring ribbon", "silk swatches"],
    dominantColors: ["violet", "moon blue", "silver"],
    expressionTier: "merchant",
    plannedExpressions: merchantExpressions,
    portraitFilePrefix: "character-220",
    identityAnchor: "same person as character-220: tall elegant half-elf, short silver bob, crescent earrings, violet measuring sash, glowing needle, moonlit tailor, moon-touched half-elf, glowing needle",
    portraitBasePrompt: "A tall moon-touched half-elf tailor with pale golden skin, short silver bob, crescent earrings, violet measuring sash, and a needle that glows faintly blue. stylized medieval fantasy merchant RPG portrait art, polished painterly-cartoon PC game UI look, slightly cartoony, beautiful, charming, expressive, entertaining, natural facial acting, clear profession silhouette, varied body shapes, rich costume accents, crop-safe bust portrait, one flat solid pure green #00FF00 background",
    negativePrompt: sharedNegativePrompt,
    questHooks: ["noble disguise", "hidden pocket request", "moon-thread delivery"],
    integrationNotes: "Fashion/cloth merchant with quest disguise hooks.",
    ancestryOrSpecies: "moon-touched half-elf",
    magicalTraits: ["faint blue glow around her needle"],
  },
  {
    characterId: "character-221",
    rosterGroup: "supporting_cast",
    runtimeIndex: 172,
    catalogKey: null,
    finalDisplayName: "Darnik Stonehush",
    profession: "Mason",
    gameplayGroups: ["trade", "company"],
    roleTags: ["stone", "mason", "repair", "construction", "tool"],
    marketFlavor: "dusty mason yard",
    voiceDirection: "short sentences, long silences, excellent eyebrows",
    tradePersonality: "construction worker who buys stone, lime, chisels, and strong gloves",
    shortStory: "Darnik repairs walls at dawn so nobody can watch him complain about the old mortar. He claims every building has a mood, and most are annoyed.",
    visualIdentity: "A compact stoneborn mason with granite-grey skin, square jaw, moss-dark eyebrows, patched canvas vest, chisel belt, and chalk dust across one cheek.",
    uniquenessTraits: ["compact stoneborn body", "granite-grey skin", "square jaw", "moss-dark eyebrows", "patched vest", "chalk cheek"],
    professionProps: ["chisel belt", "mason square", "lime pouch"],
    dominantColors: ["granite grey", "canvas tan", "chalk white"],
    expressionTier: "merchant",
    plannedExpressions: merchantExpressions,
    portraitFilePrefix: "character-221",
    identityAnchor: "same person as character-221: compact stoneborn body, granite-grey skin, square jaw, moss-dark eyebrows, patched vest, mason, stoneborn, chisel belt",
    portraitBasePrompt: "A compact stoneborn mason with granite-grey skin, square jaw, moss-dark eyebrows, patched canvas vest, chisel belt, and chalk dust across one cheek. stylized medieval fantasy merchant RPG portrait art, polished painterly-cartoon PC game UI look, slightly cartoony, beautiful, charming, expressive, entertaining, natural facial acting, clear profession silhouette, varied body shapes, rich costume accents, crop-safe bust portrait, one flat solid pure green #00FF00 background",
    negativePrompt: sharedNegativePrompt,
    questHooks: ["warehouse wall repair", "stolen chisel set", "angry building rumor"],
    integrationNotes: "Construction/craft merchant for company expansion flavor.",
    ancestryOrSpecies: "stoneborn",
    magicalTraits: [],
  },
  {
    characterId: "character-222",
    rosterGroup: "supporting_cast",
    runtimeIndex: 173,
    catalogKey: null,
    finalDisplayName: "Yul Saffronveil",
    profession: "Spice Veil Trader",
    gameplayGroups: ["trade", "collector_specialist"],
    roleTags: ["spice", "luxury", "import", "perfume", "rare_goods"],
    marketFlavor: "silk-draped spice counter",
    voiceDirection: "soft, fragrant, and full of double meanings",
    tradePersonality: "luxury importer who buys spices, perfume glass, and exotic containers",
    shortStory: "Yul sells saffron in pinches and secrets in silence. Every veil in his stall smells different, and the expensive ones remember who touched them.",
    visualIdentity: "A slender desert elf with amber skin, almond eyes lined in kohl, layered saffron and indigo veils, gold nose chain, and little glass spice vials on a sash.",
    uniquenessTraits: ["slender desert elf", "kohl-lined eyes", "saffron veils", "indigo layers", "gold nose chain", "glass spice vials"],
    professionProps: ["spice vials", "perfume glass", "silk veil"],
    dominantColors: ["saffron", "indigo", "gold"],
    expressionTier: "merchant",
    plannedExpressions: merchantExpressions,
    portraitFilePrefix: "character-222",
    identityAnchor: "same person as character-222: slender desert elf, kohl-lined eyes, saffron veils, indigo layers, gold nose chain, spice veil trader, desert elf, spice vials",
    portraitBasePrompt: "A slender desert elf with amber skin, almond eyes lined in kohl, layered saffron and indigo veils, gold nose chain, and little glass spice vials on a sash. stylized medieval fantasy merchant RPG portrait art, polished painterly-cartoon PC game UI look, slightly cartoony, beautiful, charming, expressive, entertaining, natural facial acting, clear profession silhouette, varied body shapes, rich costume accents, crop-safe bust portrait, one flat solid pure green #00FF00 background",
    negativePrompt: sharedNegativePrompt,
    questHooks: ["stolen saffron", "perfume clue", "noble spice order"],
    integrationNotes: "Luxury/spice trader and rare-goods buyer.",
    ancestryOrSpecies: "desert elf",
    magicalTraits: [],
  },
  {
    characterId: "character-223",
    rosterGroup: "supporting_cast",
    runtimeIndex: 174,
    catalogKey: null,
    finalDisplayName: "Rook Threecrows",
    profession: "Bone And Rag Picker",
    gameplayGroups: ["risk_crime", "trade"],
    roleTags: ["scrap", "bone", "rag", "recycler", "rumor"],
    marketFlavor: "crow-haunted alley cart",
    voiceDirection: "raspy, funny, and too informed about locked doors",
    tradePersonality: "scrap buyer who wants rags, bone, broken tools, and discarded oddities",
    shortStory: "Rook collects what rich people drop and poor people cannot carry. His three crows are better accountants than most clerks and worse dinner guests than most thieves.",
    visualIdentity: "A wiry old human rag picker with dark weathered skin, sharp nose, patched black cloak, crow-feather hat, bone buttons, and three small crows perched around him.",
    uniquenessTraits: ["wiry old silhouette", "sharp nose", "crow-feather hat", "patched black cloak", "bone buttons", "three crows"],
    professionProps: ["rag cart handle", "bone buttons", "crow companions"],
    dominantColors: ["crow black", "bone white", "dust grey"],
    expressionTier: "merchant",
    plannedExpressions: merchantExpressions,
    portraitFilePrefix: "character-223",
    identityAnchor: "same person as character-223: wiry old silhouette, sharp nose, crow-feather hat, patched black cloak, bone buttons, bone and rag picker, human, rag cart handle",
    portraitBasePrompt: "A wiry old human rag picker with dark weathered skin, sharp nose, patched black cloak, crow-feather hat, bone buttons, and three small crows perched around him. stylized medieval fantasy merchant RPG portrait art, polished painterly-cartoon PC game UI look, slightly cartoony, beautiful, charming, expressive, entertaining, natural facial acting, clear profession silhouette, varied body shapes, rich costume accents, crop-safe bust portrait, one flat solid pure green #00FF00 background",
    negativePrompt: sharedNegativePrompt,
    questHooks: ["lost ring in rags", "crow witness", "discarded map scrap"],
    integrationNotes: "Scrap/risk-crime rumor merchant.",
    ancestryOrSpecies: "human",
    magicalTraits: [],
  },
  {
    characterId: "character-224",
    rosterGroup: "supporting_cast",
    runtimeIndex: 175,
    catalogKey: null,
    finalDisplayName: "Tamsin Brightspoon",
    profession: "Street Cook",
    gameplayGroups: ["trade", "market_service"],
    roleTags: ["cook", "food", "street", "festival", "supplier"],
    marketFlavor: "sizzling street pan",
    voiceDirection: "cheerful, bossy, and impossible to offend for long",
    tradePersonality: "cook who buys vegetables, oil, meat, spices, and cheap plates",
    shortStory: "Tamsin feeds laborers before sunrise and nobles after midnight, charging each exactly what their pride deserves. Her lucky spoon has survived three kitchen fires and one duel.",
    visualIdentity: "A plump cheerful woman with dark curly hair in a yellow scarf, flour on her cheek, red apron, huge wooden spoon, and a sizzling pan kept inside the portrait.",
    uniquenessTraits: ["plump cheerful body", "yellow scarf", "flour cheek", "red apron", "huge spoon", "sparkling grin"],
    professionProps: ["wooden spoon", "sizzling pan", "spice pouch"],
    dominantColors: ["red", "yellow", "warm brown"],
    expressionTier: "merchant",
    plannedExpressions: merchantExpressions,
    portraitFilePrefix: "character-224",
    identityAnchor: "same person as character-224: plump cheerful body, yellow scarf, flour cheek, red apron, huge spoon, street cook, human, wooden spoon",
    portraitBasePrompt: "A plump cheerful woman with dark curly hair in a yellow scarf, flour on her cheek, red apron, huge wooden spoon, and a sizzling pan kept inside the portrait. stylized medieval fantasy merchant RPG portrait art, polished painterly-cartoon PC game UI look, slightly cartoony, beautiful, charming, expressive, entertaining, natural facial acting, clear profession silhouette, varied body shapes, rich costume accents, crop-safe bust portrait, one flat solid pure green #00FF00 background",
    negativePrompt: sharedNegativePrompt,
    questHooks: ["festival feast", "missing oil crate", "lucky spoon duel"],
    integrationNotes: "Food market-service NPC.",
    ancestryOrSpecies: "human",
    magicalTraits: [],
  },
  {
    characterId: "character-225",
    rosterGroup: "supporting_cast",
    runtimeIndex: 176,
    catalogKey: null,
    finalDisplayName: "Berek Snowhoop",
    profession: "Pack Harness Maker",
    gameplayGroups: ["travel", "trade", "company"],
    roleTags: ["pack_animal", "harness", "leather", "travel", "shipment"],
    marketFlavor: "leather awning by the stables",
    voiceDirection: "dry, practical, and kinder to mules than people",
    tradePersonality: "travel supplier who buys leather, buckles, rope, and animal feed",
    shortStory: "Berek knows every mule in town by bite pattern. He makes harnesses that survive mountain roads and quietly refuses to sell bad straps to desperate fools.",
    visualIdentity: "A broad northern human with pale freckled skin, white-blond beard, heavy green cloak, leather apron, brass buckles, and a loop of colorful harness straps.",
    uniquenessTraits: ["broad northern build", "white-blond beard", "green cloak", "leather apron", "brass buckles", "harness loops"],
    professionProps: ["harness straps", "brass buckles", "feed token"],
    dominantColors: ["forest green", "leather brown", "brass"],
    expressionTier: "merchant",
    plannedExpressions: merchantExpressions,
    portraitFilePrefix: "character-225",
    identityAnchor: "same person as character-225: broad northern build, white-blond beard, green cloak, leather apron, brass buckles, pack harness maker, human, harness straps",
    portraitBasePrompt: "A broad northern human with pale freckled skin, white-blond beard, heavy green cloak, leather apron, brass buckles, and a loop of colorful harness straps. stylized medieval fantasy merchant RPG portrait art, polished painterly-cartoon PC game UI look, slightly cartoony, beautiful, charming, expressive, entertaining, natural facial acting, clear profession silhouette, varied body shapes, rich costume accents, crop-safe bust portrait, one flat solid pure green #00FF00 background",
    negativePrompt: sharedNegativePrompt,
    questHooks: ["broken caravan strap", "stolen mule token", "mountain road prep"],
    integrationNotes: "Travel/company supplier for capacity and shipment flavor.",
    ancestryOrSpecies: "human",
    magicalTraits: [],
  },
  {
    characterId: "character-226",
    rosterGroup: "supporting_cast",
    runtimeIndex: 177,
    catalogKey: null,
    finalDisplayName: "Cela Reedwhistle",
    profession: "Basket Weaver",
    gameplayGroups: ["trade", "market_service"],
    roleTags: ["basket", "reed", "container", "craft", "farm"],
    marketFlavor: "reed mat stall",
    voiceDirection: "light, teasing, and sharper than a reed knife",
    tradePersonality: "container maker who buys reeds, dyes, twine, and farm scraps",
    shortStory: "Cela's baskets carry fruit, fish, secrets, and once a very angry rooster. She weaves whistle-holes into handles so children can find their mothers in crowded markets.",
    visualIdentity: "A slender river halfling woman with warm tan skin, bright green eyes, reed-brown braids, blue wrap dress, and armfuls of woven baskets shaped like birds.",
    uniquenessTraits: ["slender river halfling", "reed-brown braids", "green eyes", "blue wrap dress", "bird-shaped baskets", "quick smile"],
    professionProps: ["woven baskets", "reed knife", "dyed twine"],
    dominantColors: ["reed tan", "river blue", "leaf green"],
    expressionTier: "merchant",
    plannedExpressions: merchantExpressions,
    portraitFilePrefix: "character-226",
    identityAnchor: "same person as character-226: slender river halfling, reed-brown braids, green eyes, blue wrap dress, bird-shaped baskets, basket weaver, river halfling, woven baskets",
    portraitBasePrompt: "A slender river halfling woman with warm tan skin, bright green eyes, reed-brown braids, blue wrap dress, and armfuls of woven baskets shaped like birds. stylized medieval fantasy merchant RPG portrait art, polished painterly-cartoon PC game UI look, slightly cartoony, beautiful, charming, expressive, entertaining, natural facial acting, clear profession silhouette, varied body shapes, rich costume accents, crop-safe bust portrait, one flat solid pure green #00FF00 background",
    negativePrompt: sharedNegativePrompt,
    questHooks: ["secret basket delivery", "rooster incident", "missing dye bundles"],
    integrationNotes: "Container/craft merchant.",
    ancestryOrSpecies: "river halfling",
    magicalTraits: [],
  },
  {
    characterId: "character-227",
    rosterGroup: "supporting_cast",
    runtimeIndex: 178,
    catalogKey: null,
    finalDisplayName: "Idris Starbrass",
    profession: "Astrolabe Seller",
    gameplayGroups: ["travel", "collector_specialist", "quest"],
    roleTags: ["navigation", "brass", "stars", "tool", "rare_goods"],
    marketFlavor: "night-blue navigation booth",
    voiceDirection: "dreamy, scholarly, and always pointing at invisible stars",
    tradePersonality: "navigation specialist who buys brass, glass, maps, magnets, and star charts",
    shortStory: "Idris sells instruments to travelers who pretend they understand the sky. His best astrolabe once predicted a storm, a wedding, and a goat theft in the same hour.",
    visualIdentity: "A thin elderly man with deep umber skin, star-patterned blue turban, white pointed beard, brass spectacles, and a polished astrolabe glowing with tiny star points.",
    uniquenessTraits: ["thin elderly silhouette", "starry blue turban", "white pointed beard", "brass spectacles", "glowing astrolabe", "scholarly hands"],
    professionProps: ["astrolabe", "star chart", "brass compass"],
    dominantColors: ["night blue", "brass", "star white"],
    expressionTier: "merchant",
    plannedExpressions: merchantExpressions,
    portraitFilePrefix: "character-227",
    identityAnchor: "same person as character-227: thin elderly silhouette, starry blue turban, white pointed beard, brass spectacles, glowing astrolabe, astrolabe seller, human, astrolabe",
    portraitBasePrompt: "A thin elderly man with deep umber skin, star-patterned blue turban, white pointed beard, brass spectacles, and a polished astrolabe glowing with tiny star points. stylized medieval fantasy merchant RPG portrait art, polished painterly-cartoon PC game UI look, slightly cartoony, beautiful, charming, expressive, entertaining, natural facial acting, clear profession silhouette, varied body shapes, rich costume accents, crop-safe bust portrait, one flat solid pure green #00FF00 background",
    negativePrompt: sharedNegativePrompt,
    questHooks: ["wrong star chart", "storm prediction", "lost navigator"],
    integrationNotes: "Travel/navigation specialist and collector.",
    ancestryOrSpecies: "human",
    magicalTraits: ["tiny star points glowing inside the astrolabe"],
  },
  {
    characterId: "character-228",
    rosterGroup: "supporting_cast",
    runtimeIndex: 179,
    catalogKey: null,
    finalDisplayName: "Mora Pindrop",
    profession: "Needle Locksmith",
    gameplayGroups: ["market_service", "risk_crime", "trade"],
    roleTags: ["locksmith", "needle", "key", "security", "tool"],
    marketFlavor: "tiny lock repair counter",
    voiceDirection: "quiet, quick, and amused by large problems",
    tradePersonality: "security crafter who buys metal pins, fine wire, wax, and old keys",
    shortStory: "Mora repairs locks with needles thin enough to vanish in candlelight. Guards hire her for vaults, thieves hire her for advice, and she smiles at neither invoice.",
    visualIdentity: "A tiny gnome woman with coffee-brown skin, enormous dark eyes, black bob haircut, teal work coat, needle-thin lockpicks in a velvet roll, and silver thimble rings.",
    uniquenessTraits: ["tiny gnome silhouette", "huge dark eyes", "black bob haircut", "teal coat", "silver thimble rings", "velvet pick roll"],
    professionProps: ["needle lockpicks", "tiny keys", "wax impression"],
    dominantColors: ["teal", "silver", "black"],
    expressionTier: "merchant",
    plannedExpressions: merchantExpressions,
    portraitFilePrefix: "character-228",
    identityAnchor: "same person as character-228: tiny gnome silhouette, huge dark eyes, black bob haircut, teal coat, silver thimble rings, needle locksmith, gnome, needle lockpicks",
    portraitBasePrompt: "A tiny gnome woman with coffee-brown skin, enormous dark eyes, black bob haircut, teal work coat, needle-thin lockpicks in a velvet roll, and silver thimble rings. stylized medieval fantasy merchant RPG portrait art, polished painterly-cartoon PC game UI look, slightly cartoony, beautiful, charming, expressive, entertaining, natural facial acting, clear profession silhouette, varied body shapes, rich costume accents, crop-safe bust portrait, one flat solid pure green #00FF00 background",
    negativePrompt: sharedNegativePrompt,
    questHooks: ["vault repair", "forged key", "missing lockbox"],
    integrationNotes: "Security/locksmith market-service NPC.",
    ancestryOrSpecies: "gnome",
    magicalTraits: [],
  },
  {
    characterId: "character-229",
    rosterGroup: "supporting_cast",
    runtimeIndex: 180,
    catalogKey: null,
    finalDisplayName: "Varo Ashpalm",
    profession: "Charcoal Burner",
    gameplayGroups: ["trade", "travel"],
    roleTags: ["charcoal", "fuel", "wood", "camp", "supplier"],
    marketFlavor: "smoky charcoal stack",
    voiceDirection: "low, smoky, and surprisingly poetic about fire",
    tradePersonality: "fuel supplier who buys wood, sacks, cart wheels, and fireproof gloves",
    shortStory: "Varo spends weeks in the woods turning branches into black coin. He says charcoal remembers every tree it used to be, which is why good cooks listen to it crackle.",
    visualIdentity: "A lean soot-darkened man with ash-grey beard, rolled black sleeves, red scarf, charcoal sack over one shoulder, and hands permanently smudged like shadows.",
    uniquenessTraits: ["lean smoky build", "ash-grey beard", "rolled black sleeves", "red scarf", "charcoal sack", "shadow-smudged hands"],
    professionProps: ["charcoal sack", "fire hook", "wood tally"],
    dominantColors: ["charcoal black", "ash grey", "ember red"],
    expressionTier: "merchant",
    plannedExpressions: merchantExpressions,
    portraitFilePrefix: "character-229",
    identityAnchor: "same person as character-229: lean smoky build, ash-grey beard, rolled black sleeves, red scarf, charcoal sack, charcoal burner, human, charcoal sack",
    portraitBasePrompt: "A lean soot-darkened man with ash-grey beard, rolled black sleeves, red scarf, charcoal sack over one shoulder, and hands permanently smudged like shadows. stylized medieval fantasy merchant RPG portrait art, polished painterly-cartoon PC game UI look, slightly cartoony, beautiful, charming, expressive, entertaining, natural facial acting, clear profession silhouette, varied body shapes, rich costume accents, crop-safe bust portrait, one flat solid pure green #00FF00 background",
    negativePrompt: sharedNegativePrompt,
    questHooks: ["camp fuel shortage", "forest kiln dispute", "special cooking charcoal"],
    integrationNotes: "Fuel/travel supply merchant.",
    ancestryOrSpecies: "human",
    magicalTraits: [],
  },
  {
    characterId: "character-230",
    rosterGroup: "supporting_cast",
    runtimeIndex: 181,
    catalogKey: null,
    finalDisplayName: "Keffi Bluefin",
    profession: "Canal Fishmonger",
    gameplayGroups: ["trade", "market_service"],
    roleTags: ["fish", "seafood", "canal", "food", "supplier"],
    marketFlavor: "blue-tiled fish counter",
    voiceDirection: "bright, slippery, and full of canal curses",
    tradePersonality: "fish seller who buys salt, baskets, knives, barrels, and clean ice",
    shortStory: "Keffi knows which fish are fresh, which are cursed, and which have swallowed wedding rings. She can gut a trout while negotiating three prices and insulting a boatman.",
    visualIdentity: "A river-touched woman with sea-blue freckles, wet black curls, silver fish-scale earrings, rolled turquoise sleeves, and a neat tray of bright canal fish.",
    uniquenessTraits: ["river-touched face", "sea-blue freckles", "wet black curls", "fish-scale earrings", "turquoise sleeves", "quick knife hand"],
    professionProps: ["fish tray", "small fillet knife", "salt basket"],
    dominantColors: ["turquoise", "silver", "fish blue"],
    expressionTier: "merchant",
    plannedExpressions: merchantExpressions,
    portraitFilePrefix: "character-230",
    identityAnchor: "same person as character-230: river-touched face, sea-blue freckles, wet black curls, fish-scale earrings, turquoise sleeves, canal fishmonger, river-touched human, fish tray",
    portraitBasePrompt: "A river-touched woman with sea-blue freckles, wet black curls, silver fish-scale earrings, rolled turquoise sleeves, and a neat tray of bright canal fish. stylized medieval fantasy merchant RPG portrait art, polished painterly-cartoon PC game UI look, slightly cartoony, beautiful, charming, expressive, entertaining, natural facial acting, clear profession silhouette, varied body shapes, rich costume accents, crop-safe bust portrait, one flat solid pure green #00FF00 background",
    negativePrompt: sharedNegativePrompt,
    questHooks: ["ring in fish", "bad ice shipment", "cursed eel rumor"],
    integrationNotes: "Seafood/food merchant.",
    ancestryOrSpecies: "river-touched human",
    magicalTraits: ["subtle water shimmer along her fish-scale earrings"],
  },
  {
    characterId: "character-231",
    rosterGroup: "supporting_cast",
    runtimeIndex: 182,
    catalogKey: null,
    finalDisplayName: "Gunda Hearthcoil",
    profession: "Stove Tinker",
    gameplayGroups: ["trade", "company"],
    roleTags: ["stove", "metal", "repair", "kitchen", "tool"],
    marketFlavor: "warm iron repair bench",
    voiceDirection: "gravelly, proud, and offended by cold soup",
    tradePersonality: "repair merchant who buys iron parts, rivets, coal, and copper coils",
    shortStory: "Gunda builds stoves for inns, ships, and stubborn widowers who think smoke is a spice. Her best models purr when fed good coal.",
    visualIdentity: "A stocky salamander-blooded woman with coppery skin, ember-orange eyes, blacksmith arms, soot-red kerchief, and a tiny coiled stove chimney glowing softly beside her.",
    uniquenessTraits: ["stocky repair silhouette", "coppery skin", "ember eyes", "blacksmith arms", "red kerchief", "coiled stove chimney"],
    professionProps: ["stove coil", "rivet hammer", "coal scoop"],
    dominantColors: ["copper", "ember orange", "iron black"],
    expressionTier: "merchant",
    plannedExpressions: merchantExpressions,
    portraitFilePrefix: "character-231",
    identityAnchor: "same person as character-231: stocky repair silhouette, coppery skin, ember eyes, blacksmith arms, red kerchief, stove tinker, salamander-blooded human, stove coil",
    portraitBasePrompt: "A stocky salamander-blooded woman with coppery skin, ember-orange eyes, blacksmith arms, soot-red kerchief, and a tiny coiled stove chimney glowing softly beside her. stylized medieval fantasy merchant RPG portrait art, polished painterly-cartoon PC game UI look, slightly cartoony, beautiful, charming, expressive, entertaining, natural facial acting, clear profession silhouette, varied body shapes, rich costume accents, crop-safe bust portrait, one flat solid pure green #00FF00 background",
    negativePrompt: sharedNegativePrompt,
    questHooks: ["inn stove repair", "coal quality feud", "ship galley upgrade"],
    integrationNotes: "Kitchen/repair merchant for company/warehouse flavor.",
    ancestryOrSpecies: "salamander-blooded human",
    magicalTraits: ["soft ember glow in her eyes and stove coil"],
  },
  {
    characterId: "character-232",
    rosterGroup: "supporting_cast",
    runtimeIndex: 183,
    catalogKey: null,
    finalDisplayName: "Alwin Silkfern",
    profession: "Flower And Dye Seller",
    gameplayGroups: ["trade", "guild_noble"],
    roleTags: ["flowers", "dye", "luxury", "cloth", "garden"],
    marketFlavor: "flower-dye awning",
    voiceDirection: "delicate, dramatic, and ruthless about wilted petals",
    tradePersonality: "dye and flower seller who buys rare blooms, vases, cloth, and garden salts",
    shortStory: "Alwin sells bouquets to lovers and dye vats to tailors, treating both as matters of state. He once ended a noble feud with the correct shade of blue.",
    visualIdentity: "A slender greenkin man with leaf-tinted skin, soft pink eyes, fern-like hair, lavender vest, and a fan of bright flowers arranged like a peacock tail.",
    uniquenessTraits: ["slender greenkin body", "leaf-tinted skin", "fern hair", "pink eyes", "lavender vest", "flower fan"],
    professionProps: ["flower fan", "dye bottles", "ribbon scissors"],
    dominantColors: ["lavender", "leaf green", "petal pink"],
    expressionTier: "merchant",
    plannedExpressions: merchantExpressions,
    portraitFilePrefix: "character-232",
    identityAnchor: "same person as character-232: slender greenkin body, leaf-tinted skin, fern hair, pink eyes, lavender vest, flower and dye seller, greenkin, flower fan",
    portraitBasePrompt: "A slender greenkin man with leaf-tinted skin, soft pink eyes, fern-like hair, lavender vest, and a fan of bright flowers arranged like a peacock tail. stylized medieval fantasy merchant RPG portrait art, polished painterly-cartoon PC game UI look, slightly cartoony, beautiful, charming, expressive, entertaining, natural facial acting, clear profession silhouette, varied body shapes, rich costume accents, crop-safe bust portrait, one flat solid pure green #00FF00 background",
    negativePrompt: sharedNegativePrompt,
    questHooks: ["rare blue dye", "wedding bouquet panic", "poisoned petals"],
    integrationNotes: "Luxury/dye merchant.",
    ancestryOrSpecies: "greenkin",
    magicalTraits: ["tiny fresh leaves curling in his hair"],
  },
  {
    characterId: "character-233",
    rosterGroup: "supporting_cast",
    runtimeIndex: 184,
    catalogKey: null,
    finalDisplayName: "Safra Bellsand",
    profession: "Glassblower",
    gameplayGroups: ["trade", "collector_specialist"],
    roleTags: ["glass", "craft", "bottle", "luxury", "container"],
    marketFlavor: "hot glass kiln",
    voiceDirection: "musical, focused, and impatient with clumsy hands",
    tradePersonality: "glass artisan who buys sand, ash, dyes, metal rods, and rare molds",
    shortStory: "Safra blows bottles thin enough to sing when filled. Apothecaries, perfumers, and smugglers all need her work, though only one group pays before breaking things.",
    visualIdentity: "A tall desert woman with golden-brown skin, shaved head wrapped in orange cloth, long glass earrings, heat goggles on her forehead, and a glowing blue glass bubble on a blowpipe.",
    uniquenessTraits: ["tall desert silhouette", "orange head wrap", "long glass earrings", "heat goggles", "blue glass bubble", "focused eyes"],
    professionProps: ["glass blowpipe", "colored bottles", "heat goggles"],
    dominantColors: ["orange", "glass blue", "gold sand"],
    expressionTier: "merchant",
    plannedExpressions: merchantExpressions,
    portraitFilePrefix: "character-233",
    identityAnchor: "same person as character-233: tall desert silhouette, orange head wrap, long glass earrings, heat goggles, blue glass bubble, glassblower, human, glass blowpipe",
    portraitBasePrompt: "A tall desert woman with golden-brown skin, shaved head wrapped in orange cloth, long glass earrings, heat goggles on her forehead, and a glowing blue glass bubble on a blowpipe. stylized medieval fantasy merchant RPG portrait art, polished painterly-cartoon PC game UI look, slightly cartoony, beautiful, charming, expressive, entertaining, natural facial acting, clear profession silhouette, varied body shapes, rich costume accents, crop-safe bust portrait, one flat solid pure green #00FF00 background",
    negativePrompt: sharedNegativePrompt,
    questHooks: ["singing bottle order", "broken perfume batch", "smuggler glass"],
    integrationNotes: "Glass/container artisan and collector supplier.",
    ancestryOrSpecies: "human",
    magicalTraits: [],
  },
  {
    characterId: "character-234",
    rosterGroup: "supporting_cast",
    runtimeIndex: 185,
    catalogKey: null,
    finalDisplayName: "Ottek Mossboot",
    profession: "Mud Healer",
    gameplayGroups: ["trade", "quest", "travel"],
    roleTags: ["herbalist", "mud", "medicine", "swamp", "healer"],
    marketFlavor: "muddy herb mat",
    voiceDirection: "slow, kind, and wetter than expected",
    tradePersonality: "healer who buys herbs, jars, leeches, salt, and clean bandage cloth",
    shortStory: "Ottek learned medicine by falling into the right swamp and listening to frogs argue. His mud poultices smell terrible and work annoyingly well.",
    visualIdentity: "A round frog-blooded man with olive green skin, wide mouth, sleepy amber eyes, mossy boots, patchwork brown coat, and a clay jar of glowing healing mud.",
    uniquenessTraits: ["round frog-blooded body", "wide mouth", "sleepy amber eyes", "mossy boots", "patchwork coat", "mud jar"],
    professionProps: ["healing mud jar", "herb bundle", "small leech bottle"],
    dominantColors: ["olive green", "mud brown", "amber"],
    expressionTier: "merchant",
    plannedExpressions: merchantExpressions,
    portraitFilePrefix: "character-234",
    identityAnchor: "same person as character-234: round frog-blooded body, wide mouth, sleepy amber eyes, mossy boots, patchwork coat, mud healer, frog-blooded human, healing mud jar",
    portraitBasePrompt: "A round frog-blooded man with olive green skin, wide mouth, sleepy amber eyes, mossy boots, patchwork brown coat, and a clay jar of glowing healing mud. stylized medieval fantasy merchant RPG portrait art, polished painterly-cartoon PC game UI look, slightly cartoony, beautiful, charming, expressive, entertaining, natural facial acting, clear profession silhouette, varied body shapes, rich costume accents, crop-safe bust portrait, one flat solid pure green #00FF00 background",
    negativePrompt: sharedNegativePrompt,
    questHooks: ["swamp cure", "lost leech bottle", "mud ingredient route"],
    integrationNotes: "Medicine/herbalist NPC with travel hooks.",
    ancestryOrSpecies: "frog-blooded human",
    magicalTraits: ["faint green glow inside the healing mud jar"],
  },
  {
    characterId: "character-235",
    rosterGroup: "supporting_cast",
    runtimeIndex: 186,
    catalogKey: null,
    finalDisplayName: "Piero Paintedmask",
    profession: "Festival Mask Carver",
    gameplayGroups: ["trade", "quest", "market_service"],
    roleTags: ["mask", "festival", "wood", "costume", "craft"],
    marketFlavor: "bright carnival carving stall",
    voiceDirection: "flamboyant, laughing, and secretly observant",
    tradePersonality: "festival crafter who buys wood, paint, feathers, cloth, and bells",
    shortStory: "Piero carves masks that reveal exactly what customers hoped to hide. During festivals he sells joy; after midnight he sells disguises.",
    visualIdentity: "A lean human man with warm tan skin, curled moustache, purple waistcoat, sleeves covered in paint, feathered mask pushed onto his forehead, and a half-carved smiling mask in hand.",
    uniquenessTraits: ["lean theatrical pose", "curled moustache", "purple waistcoat", "painted sleeves", "feathered forehead mask", "half-carved mask"],
    professionProps: ["carved mask", "paintbrush", "little bells"],
    dominantColors: ["purple", "paint red", "feather gold"],
    expressionTier: "merchant",
    plannedExpressions: merchantExpressions,
    portraitFilePrefix: "character-235",
    identityAnchor: "same person as character-235: lean theatrical pose, curled moustache, purple waistcoat, painted sleeves, feathered forehead mask, festival mask carver, human, carved mask",
    portraitBasePrompt: "A lean human man with warm tan skin, curled moustache, purple waistcoat, sleeves covered in paint, feathered mask pushed onto his forehead, and a half-carved smiling mask in hand. stylized medieval fantasy merchant RPG portrait art, polished painterly-cartoon PC game UI look, slightly cartoony, beautiful, charming, expressive, entertaining, natural facial acting, clear profession silhouette, varied body shapes, rich costume accents, crop-safe bust portrait, one flat solid pure green #00FF00 background",
    negativePrompt: sharedNegativePrompt,
    questHooks: ["festival disguise", "mask that knows lies", "paint delivery"],
    integrationNotes: "Festival/costume merchant and disguise quest source.",
    ancestryOrSpecies: "human",
    magicalTraits: [],
  },
  {
    characterId: "character-236",
    rosterGroup: "supporting_cast",
    runtimeIndex: 187,
    catalogKey: null,
    finalDisplayName: "Deya Thistlequill",
    profession: "Street Scribe",
    gameplayGroups: ["market_service", "quest", "trade"],
    roleTags: ["scribe", "letter", "contract", "rumor", "paper"],
    marketFlavor: "paper booth under a striped shade",
    voiceDirection: "quick, dry, and allergic to bad grammar",
    tradePersonality: "scribe who buys ink, paper, wax, quills, and sealed letters",
    shortStory: "Deya writes love letters, debt notices, and apologies for people too proud to hold a pen. She never reads private messages aloud, but her eyebrows remember everything.",
    visualIdentity: "A sharp-faced young woman with umber skin, short coiled hair, ink-stained fingertips, striped blue shawl, thistle quill tucked behind one ear, and a stack of folded letters.",
    uniquenessTraits: ["sharp-faced young woman", "short coiled hair", "ink-stained fingers", "blue striped shawl", "thistle quill", "expressive eyebrows"],
    professionProps: ["thistle quill", "folded letters", "wax seal"],
    dominantColors: ["ink blue", "paper cream", "seal red"],
    expressionTier: "merchant",
    plannedExpressions: merchantExpressions,
    portraitFilePrefix: "character-236",
    identityAnchor: "same person as character-236: sharp-faced young woman, short coiled hair, ink-stained fingers, blue striped shawl, thistle quill, street scribe, human, thistle quill",
    portraitBasePrompt: "A sharp-faced young woman with umber skin, short coiled hair, ink-stained fingertips, striped blue shawl, thistle quill tucked behind one ear, and a stack of folded letters. stylized medieval fantasy merchant RPG portrait art, polished painterly-cartoon PC game UI look, slightly cartoony, beautiful, charming, expressive, entertaining, natural facial acting, clear profession silhouette, varied body shapes, rich costume accents, crop-safe bust portrait, one flat solid pure green #00FF00 background",
    negativePrompt: sharedNegativePrompt,
    questHooks: ["forged apology", "secret letter courier", "contract wording dispute"],
    integrationNotes: "Scribe/contract market-service NPC.",
    ancestryOrSpecies: "human",
    magicalTraits: [],
  },
  {
    characterId: "character-237",
    rosterGroup: "supporting_cast",
    runtimeIndex: 188,
    catalogKey: null,
    finalDisplayName: "Brannox Gulltoe",
    profession: "Dock Porter",
    gameplayGroups: ["company", "travel", "trade"],
    roleTags: ["dock", "porter", "cargo", "warehouse", "shipment"],
    marketFlavor: "busy dock crate stack",
    voiceDirection: "booming, cheerful, and always counting under his breath",
    tradePersonality: "cargo worker who buys rope, gloves, hooks, and cheap food in bulk",
    shortStory: "Brannox can carry two barrels and still notice if one coin is missing from a pouch. He knows the names of every ship, crate, and gull that has ever insulted him.",
    visualIdentity: "A huge friendly man with sunburned skin, shaved head, braided beard beads shaped like gulls, sleeveless blue tunic, rope harness, and a wooden crate balanced safely against his side.",
    uniquenessTraits: ["huge porter build", "sunburned skin", "shaved head", "gull beard beads", "blue tunic", "rope harness"],
    professionProps: ["wooden crate", "cargo hook", "rope harness"],
    dominantColors: ["dock blue", "rope tan", "sun red"],
    expressionTier: "merchant",
    plannedExpressions: merchantExpressions,
    portraitFilePrefix: "character-237",
    identityAnchor: "same person as character-237: huge porter build, sunburned skin, shaved head, gull beard beads, blue tunic, dock porter, human, wooden crate",
    portraitBasePrompt: "A huge friendly man with sunburned skin, shaved head, braided beard beads shaped like gulls, sleeveless blue tunic, rope harness, and a wooden crate balanced safely against his side. stylized medieval fantasy merchant RPG portrait art, polished painterly-cartoon PC game UI look, slightly cartoony, beautiful, charming, expressive, entertaining, natural facial acting, clear profession silhouette, varied body shapes, rich costume accents, crop-safe bust portrait, one flat solid pure green #00FF00 background",
    negativePrompt: sharedNegativePrompt,
    questHooks: ["missing crate", "dock strike", "gull-stolen token"],
    integrationNotes: "Dock/warehouse/shipment support NPC.",
    ancestryOrSpecies: "human",
    magicalTraits: [],
  },
  {
    characterId: "character-238",
    rosterGroup: "supporting_cast",
    runtimeIndex: 189,
    catalogKey: null,
    finalDisplayName: "Noll Pebblecap",
    profession: "Market Sweeper",
    gameplayGroups: ["market_service"],
    roleTags: ["sweeper", "rumor", "street", "minor"],
    marketFlavor: "early morning market lane",
    voiceDirection: "small, matter-of-fact, and weirdly well informed",
    tradePersonality: "minor rumor source who accepts cheap food, old brooms, and kindness",
    shortStory: "Noll sweeps up straw, coins, and secrets before the stalls open. People forget he is there, which is why he knows who met behind the fish barrels.",
    visualIdentity: "A tiny goblin market sweeper with moss-green skin, enormous ears, patched brown cap, twig broom, and a pouch full of found buttons.",
    uniquenessTraits: ["tiny goblin silhouette", "enormous ears", "patched cap", "twig broom", "button pouch", "watchful eyes"],
    professionProps: ["twig broom", "button pouch"],
    dominantColors: ["moss green", "brown", "button brass"],
    expressionTier: "minor",
    plannedExpressions: minorExpressions,
    portraitFilePrefix: "character-238",
    identityAnchor: "same person as character-238: tiny goblin silhouette, enormous ears, patched cap, twig broom, button pouch, market sweeper, goblin, twig broom",
    portraitBasePrompt: "A tiny goblin market sweeper with moss-green skin, enormous ears, patched brown cap, twig broom, and a pouch full of found buttons. stylized medieval fantasy merchant RPG portrait art, polished painterly-cartoon PC game UI look, slightly cartoony, beautiful, charming, expressive, entertaining, natural facial acting, clear profession silhouette, varied body shapes, rich costume accents, crop-safe bust portrait, one flat solid pure green #00FF00 background",
    negativePrompt: sharedNegativePrompt,
    questHooks: ["lost coin trail", "overheard meeting", "button clue"],
    integrationNotes: "Minor rumor/source NPC.",
    ancestryOrSpecies: "goblin",
    magicalTraits: [],
  },
  {
    characterId: "character-239",
    rosterGroup: "supporting_cast",
    runtimeIndex: 190,
    catalogKey: null,
    finalDisplayName: "Auntie Vessa Rainbowl",
    profession: "Well Watcher",
    gameplayGroups: ["market_service", "quest"],
    roleTags: ["well", "water", "rumor", "minor", "town"],
    marketFlavor: "old stone well",
    voiceDirection: "warm, scolding, and impossible to hurry",
    tradePersonality: "minor town contact who trades gossip for soap, rope, and fresh fruit",
    shortStory: "Vessa watches the town well because water hears everything first. She remembers births, scandals, droughts, and the names of merchants who watered wine.",
    visualIdentity: "An elderly dark-skinned woman with soft round cheeks, silver headwrap, blue shawl, wooden water ladle, and a little rainbow bead necklace.",
    uniquenessTraits: ["elderly round face", "silver headwrap", "blue shawl", "water ladle", "rainbow beads", "gentle scolding eyes"],
    professionProps: ["wooden water ladle", "rainbow bead necklace"],
    dominantColors: ["water blue", "silver", "rainbow beads"],
    expressionTier: "minor",
    plannedExpressions: minorExpressions,
    portraitFilePrefix: "character-239",
    identityAnchor: "same person as character-239: elderly round face, silver headwrap, blue shawl, water ladle, rainbow beads, well watcher, human, wooden water ladle",
    portraitBasePrompt: "An elderly dark-skinned woman with soft round cheeks, silver headwrap, blue shawl, wooden water ladle, and a little rainbow bead necklace. stylized medieval fantasy merchant RPG portrait art, polished painterly-cartoon PC game UI look, slightly cartoony, beautiful, charming, expressive, entertaining, natural facial acting, clear profession silhouette, varied body shapes, rich costume accents, crop-safe bust portrait, one flat solid pure green #00FF00 background",
    negativePrompt: sharedNegativePrompt,
    questHooks: ["dry well rumor", "watered wine accusation", "lost bucket"],
    integrationNotes: "Minor town rumor NPC.",
    ancestryOrSpecies: "human",
    magicalTraits: [],
  },
  {
    characterId: "character-240",
    rosterGroup: "supporting_cast",
    runtimeIndex: 191,
    catalogKey: null,
    finalDisplayName: "Qadir Mothlamp",
    profession: "Night Lamplighter",
    gameplayGroups: ["travel", "market_service"],
    roleTags: ["lamp", "night", "street", "minor", "safety"],
    marketFlavor: "lamp-lit alley at dusk",
    voiceDirection: "hushed, poetic, and slightly afraid of daylight",
    tradePersonality: "minor night worker who buys lamp oil, wicks, and spare glass",
    shortStory: "Qadir lights the city after honest shops close and dishonest ones open. His moths find trouble before guards do, though they charge only in crumbs.",
    visualIdentity: "A thin young man with deep brown skin, sleepy eyes, charcoal hood, long yellow scarf, brass lantern pole, and three pale moths glowing near the flame.",
    uniquenessTraits: ["thin lamplighter silhouette", "sleepy eyes", "charcoal hood", "long yellow scarf", "brass lantern pole", "glowing moths"],
    professionProps: ["lantern pole", "oil flask", "wick bundle"],
    dominantColors: ["charcoal", "lamp yellow", "brass"],
    expressionTier: "minor",
    plannedExpressions: minorExpressions,
    portraitFilePrefix: "character-240",
    identityAnchor: "same person as character-240: thin lamplighter silhouette, sleepy eyes, charcoal hood, long yellow scarf, brass lantern pole, night lamplighter, human, lantern pole",
    portraitBasePrompt: "A thin young man with deep brown skin, sleepy eyes, charcoal hood, long yellow scarf, brass lantern pole, and three pale moths glowing near the flame. stylized medieval fantasy merchant RPG portrait art, polished painterly-cartoon PC game UI look, slightly cartoony, beautiful, charming, expressive, entertaining, natural facial acting, clear profession silhouette, varied body shapes, rich costume accents, crop-safe bust portrait, one flat solid pure green #00FF00 background",
    negativePrompt: sharedNegativePrompt,
    questHooks: ["night route warning", "missing oil", "moth witness"],
    integrationNotes: "Minor night/travel warning NPC.",
    ancestryOrSpecies: "human",
    magicalTraits: ["three pale moths glowing near the lantern flame"],
  },
] as const satisfies readonly FinalCharacterIdentityProfile[];

export const characterIdentityCatalogCastBatch06 = {
  batchId: "identity-catalog-cast-batch-006",
  status: "profile_locked",
  rosterScope: "Final 30 supporting cast slots: runtime indexes 162-191. This completes the 192 visible supporting cast target while preserving runtime anchors as mechanical anchors.",
  portraitManifestLocked: true,
  notes: [
    "This final supporting cast batch defines current runtime-facing identity data while runtime anchors stay stable.",
    "The 30 identities produce 96 portrait prompts arranged as eight complete 3x4 sheets.",
    "Character profiles are locked against accidental manifest drift.",
    "Character prompt files support portrait manifest validation.",
    "The runtime portrait gate controls asset readiness.",
  ],
  identities: finalSupportingCastIdentities,
} as const satisfies CharacterIdentityCatalogBatch;

export const characterIdentityCatalogCastBatch06PortraitImageCount = getIdentityBatchPortraitImageCount(
  characterIdentityCatalogCastBatch06,
);
