import type { CharacterQuestline } from "./questTypes";

export const characterQuestlines: CharacterQuestline[] = [
  {
    id: "questline-mara-night-baker",
    npcId: "character-010",
    npcName: "Mara the Night Baker",
    theme: "Food, pride, worker trust, and whether help becomes dependency.",
    summary: "Mara's arc follows a bakery that feeds working people at night. The player can make her an independent supplier, a loyal company partner, a cautious ally, or a critic who remembers being exploited.",
    quests: [
      { title: "Bread Before Dawn", premise: "Her missing flour threatens the bakery before sunrise.", choicePressure: "Solve the crisis through replacement, truth, theft, or profit.", possibleOutcomes: ["loyal supplier", "cautious ally", "resentful debtor", "public critic"] },
      { title: "The Burned Oven", premise: "Her oven cracks after suspicious sabotage.", choicePressure: "Fund repairs fairly, negotiate a contract, or buy leverage.", possibleOutcomes: ["bakery restored", "supplier tie formed", "ownership pressure created"] },
      { title: "A Contract of Crumbs", premise: "The workers' guild offers a thin contract that may trap her.", choicePressure: "Renegotiate terms or profit quietly from the contract.", possibleOutcomes: ["fair guild contract", "company supply deal", "hidden commission scandal"] },
      { title: "The Baker's Guild Vote", premise: "Mara can influence food policy if she survives earlier choices.", choicePressure: "Support her independence or fold her into company power.", possibleOutcomes: ["food ally", "company employee", "workers' advocate", "rival speaker"] },
    ],
    finalOutcomes: ["Mara becomes a reliable food supplier.", "Mara joins the company as a food-contract specialist.", "Mara stays independent but supports the player publicly.", "Mara opposes exploitative company endings."],
  },
  {
    id: "questline-ivor-route-scout",
    npcId: "character-021",
    npcName: "Ivor the Route Scout",
    theme: "Road truth, risk, and the price of safe passage.",
    summary: "Ivor knows which roads are safe and which are only called safe because someone profits from silence. His trust can unlock route previews, but using him carelessly puts scouts in danger.",
    quests: [
      { title: "The Road Tax", premise: "Ivor helps compare unequal tolls.", choicePressure: "Expose toll abuse, bargain a rate, or bribe through.", possibleOutcomes: ["free-road score", "private toll discount", "scout distrust"] },
      { title: "Maps With Missing Roads", premise: "A mapmaker erases free roads from new charts.", choicePressure: "Publish truth, sell better maps, or keep routes private.", possibleOutcomes: ["public map access", "map business", "secret route advantage"] },
      { title: "The Bridge That Lied", premise: "A road is marked unsafe after a guild buys the alternate toll road.", choicePressure: "Repair truth, profit from detours, or pressure both sides.", possibleOutcomes: ["safer roads", "guild anger", "private route rights"] },
    ],
    finalOutcomes: ["Ivor becomes a trusted route advisor.", "Ivor sells route intelligence at a premium.", "Ivor leaves if scouts are repeatedly sacrificed for profit."],
  },
  {
    id: "questline-sable-auction-clerk",
    npcId: "character-030",
    npcName: "Sable of the Auction House",
    theme: "Inside information, debt, and auction trust.",
    summary: "Sable can open the auction system to the player, but her family debt creates pressure to bend the rules. Her path decides whether auctions become fair opportunity or quiet corruption.",
    quests: [
      { title: "A Friend in the Auction House", premise: "Sable offers early lot information for help with a debt.", choicePressure: "Help without cheating, use limited preview, or rig bids.", possibleOutcomes: ["trusted access", "inside preview", "auction heat"] },
      { title: "The Auction of Broken Things", premise: "A hidden valuable item sits in a widow's damaged lot.", choicePressure: "Inform, broker, or secretly bid.", possibleOutcomes: ["widow helped", "collector ally", "secret profit"] },
      { title: "Hammerfall Night", premise: "A final auction becomes a public test of Sable's integrity and the player's influence.", choicePressure: "Protect the auction, control it, or expose all of it.", possibleOutcomes: ["fair auction reform", "private auction ring", "Sable resigns"] },
    ],
    finalOutcomes: ["Sable grants fair auction previews.", "Sable joins a shadow auction network.", "Sable becomes a reformer who supports fair-trade endings."],
  },
  {
    id: "questline-orren-weighmaster",
    npcId: "character-028",
    npcName: "Orren the Weighmaster",
    theme: "Standards, shame, and official cheating.",
    summary: "Orren works inside a dishonest weighhouse. The player can make him a whistleblower, a private asset, or an enemy who protects manipulated scales.",
    quests: [
      { title: "The False Scale", premise: "Official weights are shaving value from independents.", choicePressure: "Expose, reform quietly, or exploit the cheat.", possibleOutcomes: ["public reform", "private leverage", "market scandal"] },
      { title: "Weights in the Rain", premise: "A second scale is altered for wet cargo.", choicePressure: "Teach merchants to check, or sell verification services.", possibleOutcomes: ["inspection service", "public education", "guild suspicion"] },
      { title: "The Standard Room", premise: "The original standard weights are locked away before the guild vote.", choicePressure: "Recover them legally, steal them, or forge replacements.", possibleOutcomes: ["fair standards", "legal heat", "false reform"] },
    ],
    finalOutcomes: ["Orren becomes a standards inspector ally.", "Orren becomes a compromised tool.", "Orren testifies against the player if exploited."],
  },
  {
    id: "questline-vela-ledger-copyist",
    npcId: "character-014",
    npcName: "Vela the Ledger Copyist",
    theme: "Records, fear, and whether truth should be public.",
    summary: "Vela copies records for people powerful enough to rewrite them. Her arc feeds the main ledger mystery and can decide whether evidence becomes public trust or private control.",
    quests: [
      { title: "The Clerk Who Lied", premise: "A falsified record is about to enter the guild archive.", choicePressure: "Accuse, bargain, or hide evidence.", possibleOutcomes: ["public proof", "private lead", "hidden leverage"] },
      { title: "The Ink That Fades", premise: "Contracts disappear because of special ink.", choicePressure: "Publish the flaw, recall quietly, or keep the formula.", possibleOutcomes: ["contract reform", "quiet fix", "dangerous tool"] },
      { title: "Copies for the Vote", premise: "Evidence must be copied before the guildmasters can destroy originals.", choicePressure: "Distribute widely or limit evidence to allies.", possibleOutcomes: ["public truth", "coalition leverage", "document theft"] },
    ],
    finalOutcomes: ["Vela becomes the player's archivist.", "Vela publishes independently.", "Vela vanishes if the player repeatedly weaponizes her work."],
  },
  {
    id: "questline-tamsin-warehouse-keeper",
    npcId: "character-036",
    npcName: "Tamsin the Warehouse Keeper",
    theme: "Storage, custody, and what disappears behind locked doors.",
    summary: "Tamsin controls storage access and knows how goods vanish. Her trust can unlock warehouse systems; her fear can hide fires, thefts, and false insurance.",
    quests: [
      { title: "The Warehouse Fire", premise: "A suspicious fire hides missing stock.", choicePressure: "Expose fraud, force rebuilding, or blackmail the owner.", possibleOutcomes: ["public trust", "warehouse access", "shadow leverage"] },
      { title: "Salt in the Bookroom", premise: "Improvised storage damages a library.", choicePressure: "Move goods properly, split fees, or profit from damage.", possibleOutcomes: ["clean storage", "shared liability", "cheap damaged books"] },
      { title: "Keys Without Teeth", premise: "Warehouse keys are copied before a shipment arrives.", choicePressure: "Delay, trap, or use the theft.", possibleOutcomes: ["secure warehouse", "caught thief", "hidden access"] },
    ],
    finalOutcomes: ["Tamsin manages company warehouse rules.", "Tamsin sells storage secrets.", "Tamsin locks the player out after exploitation."],
  },
  {
    id: "questline-maelis-dye-master",
    npcId: "character-011",
    npcName: "Maelis the Dye Master",
    theme: "Craft pride, color scarcity, and festival pressure.",
    summary: "Maelis' dye-house gives the game a craft supplier whose relationship can produce special goods, festival contracts, and guild conflicts over quality.",
    quests: [
      { title: "The Dye-House Deadline", premise: "Blue pigment must arrive before festival inspection.", choicePressure: "Deliver, substitute, or expose sabotage.", possibleOutcomes: ["license saved", "quality compromised", "rival exposed"] },
      { title: "Color Under Contract", premise: "A noble wants exclusive dye rights that would starve smaller clothiers.", choicePressure: "Accept money, protect access, or create tiers.", possibleOutcomes: ["exclusive profit", "public supplier", "tiered contract"] },
      { title: "The Unfading Banner", premise: "Maelis can make a signature company color if the player earns her respect.", choicePressure: "Pay, help, or pressure her into branding.", possibleOutcomes: ["company visual identity", "craft ally", "resentful supplier"] },
    ],
    finalOutcomes: ["Maelis supplies unique dyes.", "Maelis supports fair craft access.", "Maelis refuses company branding after coercion."],
  },
  {
    id: "questline-brann-counting-house",
    npcId: "character-016",
    npcName: "Brann of the Counting House",
    theme: "Credit, hidden theft, and institutional trust.",
    summary: "Brann's arc determines whether the player gains credit tools through honest banking, private leverage, or compromised silence.",
    quests: [
      { title: "The Counting-Room Rat", premise: "Missing coin is blamed on rats after seals are opened.", choicePressure: "Investigate quietly, expose publicly, or sell silence.", possibleOutcomes: ["clean counting room", "public scandal", "private debtor"] },
      { title: "The Small Loan Line", premise: "Small merchants need credit but the counting house fears defaults.", choicePressure: "Guarantee, insure, or buy debt.", possibleOutcomes: ["credit access", "insurance fees", "debt leverage"] },
      { title: "Collateral Day", premise: "The player's company can access larger loans if earlier trust holds.", choicePressure: "Secure transparent credit or hidden terms.", possibleOutcomes: ["company credit", "shadow finance", "loan denial"] },
    ],
    finalOutcomes: ["Brann offers company credit.", "Brann becomes a hidden financier.", "Brann refuses support after public humiliation."],
  },
  {
    id: "questline-nessa-fishmonger",
    npcId: "character-038",
    npcName: "Nessa the Fishmonger",
    theme: "Perishable goods, silence, and reputation at the docks.",
    summary: "Nessa's fish trade turns freshness, rumor, intimidation, and dock politics into a relationship line that can affect harbor supply.",
    quests: [
      { title: "The Fishmonger's Silence", premise: "Nessa refuses one supplier and will not say why.", choicePressure: "Test quality, mediate debt, or corner supply.", possibleOutcomes: ["safe fish", "settled debt", "private monopoly"] },
      { title: "Ice at Sunrise", premise: "Ice delivery delays threaten all morning fish stalls.", choicePressure: "Import ice, ration it, or sell priority.", possibleOutcomes: ["freshness stabilized", "priority scandal", "Nessa's trust"] },
      { title: "The Harbor Smell", premise: "A smear campaign makes the fish row look unsafe before an inspection.", choicePressure: "Find proof or profit from panic.", possibleOutcomes: ["dock trust", "rival exposed", "market fear"] },
    ],
    finalOutcomes: ["Nessa becomes a freshness advisor.", "Nessa routes seafood through the company.", "Nessa warns others if the player exploits food panic."],
  },
  {
    id: "questline-cassian-rival-merchant",
    npcId: "character-041",
    npcName: "Cassian the Rival Merchant",
    theme: "Respect, competition, and whether rivalry becomes hatred or alliance.",
    summary: "Cassian is not just an enemy. He tests whether the player wins through better trade, better ethics, better manipulation, or ruthless control.",
    quests: [
      { title: "A Price Too Clean", premise: "Cassian appears near a suspicious bargain.", choicePressure: "Outperform him without becoming him.", possibleOutcomes: ["respect", "resentment", "private rivalry"] },
      { title: "The Price-Fixing Dinner", premise: "Cassian attends the conspiracy dinner with his own motive.", choicePressure: "Join, expose, or outmaneuver him.", possibleOutcomes: ["rival anger", "temporary alliance", "shared corruption"] },
      { title: "The Rival's Ledger", premise: "Cassian holds a second ledger.", choicePressure: "Destroy, merge, publish, or reconcile evidence.", possibleOutcomes: ["rival defeat", "rival alliance", "truth crisis"] },
    ],
    finalOutcomes: ["Cassian becomes the final rival.", "Cassian becomes a reluctant ally.", "Cassian exposes the player if shadow choices dominate."],
  },
];
